apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: {{ .Values.pool.name }}
spec:
  {{- if not .Values.l2Announcements.announceOnControlPlane }}
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  {{- end }}
  interfaces:
    {{- toYaml .Values.l2Announcements.interfaces | nindent 4 }}
  externalIPs: false
  loadBalancerIPs: true
